config/routes.rb
Rails.application.routes.draw do

  resources :users
  get 'main/index'

  resources :socks
  root 'main#index'

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sock.rb
class Sock < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private

    def current_user
    	@current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @recent_socks = Sock.paginate(:page => params[:page], :per_page => 9)
    @current_sock = @recent_socks[0]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/socks_controller.rb
class SocksController < ApplicationController
  before_action :set_sock, only: [:show, :edit, :update, :destroy]

  def action1
    @current_sock = Sock.all[2]
  end

  # GET /socks
  # GET /socks.json
  def index
    @socks = Sock.all
  end

  # GET /socks/1
  # GET /socks/1.json
  def show
  end

  # GET /socks/new
  def new
    @sock = Sock.new
  end

  # GET /socks/1/edit
  def edit
  end

  # POST /socks
  # POST /socks.json
  def create
    @sock = Sock.new(sock_params)

    respond_to do |format|
      if @sock.save
        format.html { redirect_to @sock, notice: 'Sock was successfully created.' }
        format.json { render :show, status: :created, location: @sock }
      else
        format.html { render :new }
        format.json { render json: @sock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /socks/1
  # PATCH/PUT /socks/1.json
  def update
    respond_to do |format|
      if @sock.update(sock_params)
        format.html { redirect_to @sock, notice: 'Sock was successfully updated.' }
        format.json { render :show, status: :ok, location: @sock }
      else
        format.html { render :edit }
        format.json { render json: @sock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socks/1
  # DELETE /socks/1.json
  def destroy
    @sock.destroy
    respond_to do |format|
      format.html { redirect_to socks_url, notice: 'Sock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sock
      @sock = Sock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sock_params
      params.require(:sock).permit(:name, :price, :size, :color, :damages, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/socks_helper.rb
module SocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<div class="menu", 
  style="width: 50px; 
  display: inline-flex; 
  padding: 10px; 
  flex-direction: column; 
  height:calc(100vh - 20px); 
  justify-content: space-between; 
  background-color: rgb(33,36,38);
  position: fixed;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", :style => "width: 50px" %>
  <% end %>
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "user.png", :style => "width: 50px" %>
    <% end %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "bascket.png", :style => "width: 50px" %>
    <% end %>
  </div>
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", :style => "width: 50px" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="display: flex; height: 100vh">
      <%= render "layouts/menu" %>

      <%if notice%>
        <p id="notice" style="padding: 25px; background-color: green; color: white;">
          <%= notice %>
        </p>
      <%end%>
      <div 
        style="display: inline-block; 
        width: 100%; 
        padding: 20px;
        margin-left: 50px">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1 style="text-align: center">Find your perfect match!</h1>
<div style="display: flex; align-items: flex-start">
    <%= render "socks/socks" , list: @recent_socks %>
</div>

app/views/socks/_form.html.erb
<%= form_with(model: sock, local: true) do |form| %>
  <% if sock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sock.errors.count, "error") %> prohibited this sock from being saved:</h2>

      <ul>
      <% sock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sock_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :sock_price %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :sock_size %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :sock_color %>
  </div>

  <div class="field">
    <%= form.label :damages %>
    <%= form.text_field :damages, id: :sock_damages %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :sock_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/socks/_sock_description.html.erb
<div>
    <%= image_tag "1.png", :style => "width: 200px; margin: 0 auto;" %></br>
    <%= sock.name %></br>
    <%= sock.description %></br>
    <%= sock.description %></br>
    <%= sock.description %></br>
    <%= sock.description %></br>
</div>

app/views/socks/_socks.html.erb
<div>
    <% list.each do |sock| %>
        <div
            style="display: inline-flex;
            flex-direction: column; 
            padding: 30px;
            width: 300px;" >
            <%= image_tag "#{sock.id%5 +1}.png", :style => "width: 200px; margin: 0 auto;" %></br>
            <div 
                style="background-color: white;
                margin: 0 auto;
                min-width: 80px;
                border-radius: 17px;
                text-align: center;
                color: rgb(80, 84, 86);
                display: inline-block;
                padding: 5px;">
                <%= sock.name %></br>
                <%= sock.description %></br>
            </div>
            <div 
                style="background: linear-gradient(to top right, rgb(240, 11, 172), rgb(248, 179, 110));
                margin-top: -75px;
                width: 80px;
                height: 80px;
                border-radius: 50%;
                text-align: center;
                line-height: 80px;
                position: relative;
                right: -220px;
                top: -100px;">
                <%= "#{sock.price} PLN" %>
            </div>
            <hr 
                style="background: radial-gradient(circle, #000, #fff); 
                height: 1px; 
                width: 100%;
                border-width:0px;"/>
        </div>
        <hr 
            style="display: inline-flex;
            flex-direction: column;
            background: radial-gradient(circle, #000, #fff);
            height: 250px;
            border-width: 0px;
            width: 1px;"/>
    <% end %>
    <%= will_paginate list %>
</div>

app/views/socks/edit.html.erb
<h1>Editing Sock</h1>

<%= render 'form', sock: @sock %>

<%= link_to 'Show', @sock %> |
<%= link_to 'Back', socks_path %>

app/views/socks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Socks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Size</th>
      <th>Color</th>
      <th>Damages</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @socks.each do |sock| %>
      <tr>
        <td><%= sock.name %></td>
        <td><%= sock.price %></td>
        <td><%= sock.size %></td>
        <td><%= sock.color %></td>
        <td><%= sock.damages %></td>
        <td><%= sock.description %></td>
        <td><%= link_to 'Show', sock %></td>
        <td><%= link_to 'Edit', edit_sock_path(sock) %></td>
        <td><%= link_to 'Destroy', sock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sock', new_sock_path %>

app/views/socks/new.html.erb
<h1>New Sock</h1>

<%= render 'form', sock: @sock %>

<%= link_to 'Back', socks_path %>

app/views/socks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sock.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sock.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @sock.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @sock.color %>
</p>

<p>
  <strong>Damages:</strong>
  <%= @sock.damages %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sock.description %>
</p>

<%= link_to 'Edit', edit_sock_path(@sock) %> |
<%= link_to 'Back', socks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>